# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Modak Genomics
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Genome wide association study is an approach that involves rapidly scanning markers across complete sets of DNA, or genomes of numerous people to find differences associated to a particular type of disease. Once new differences are identified, then they are analysed by the researchers and cure for those variations are found.

  This study helps to develop customized medicines depending on various factors that affect the subject, thereby reducing the risk of side effects and increasing the effectiveness.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: modakanalytics
github_username:  ModakGenomics

# Build settings
markdown: kramdown
theme: minima

show_excerpts: true

masthead: /assets/Logo-Genomics.png

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - post.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: modakanalytics
    github:  ModakGenomics
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll